version: '3'
services:
  writefreely:
    image: ubuntu:24.04
    entrypoint: "/entrypoint.sh"
    volumes:
      - "./data:/opt/writefreely"
      - "./entrypoint.sh:/entrypoint.sh"
    ports:
      - 8080:8080
    environment:
      - VERSION=0.15.1
